services:
  chess:
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - MONGO_SERVER=my-mongodb
    build: .
  db:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
